name: Docker Image CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [teaspeak_update]
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.5.6'


jobs:
  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      VERSION: "1.5.6"
    steps:

    - name: Set variables for workflow
      run: |
        WORKFLOW_VERSION=$(echo ${{ github.event.inputs.version }}) \
        && if [[ -n $WORKFLOW_VERSION ]] ; \
        then echo "VERSION=$WORKFLOW_VERSION" >> $GITHUB_ENV ; fi

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build teaspeak
      run: | 
        docker build . \
        --build-arg VERSION=$VERSION \
        --tag ghcr.io/$GITHUB_ACTOR/teaspeak:latest \
        --tag ghcr.io/$GITHUB_ACTOR/teaspeak:$VERSION \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/teaspeak:$VERSION \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/teaspeak:latest \
        --push
